### ISSUE TITLE
Other Image

### ISSUE THREAD

**Issue by destata** [williammalone/Simple-Drawing-App-with-Bucket-Tool#1]
How to make it possible with  .jpg file ?

**Comment by williammalone** [comment]
The current example expects a transparent PNG for the outline image to prevent aliasing. To draw a non-transparent image (e.g. JPG) the image will need to be rendered below the drawing. You can do this by calling the `context.drawImage` method at the beginning of the `redraw` function with a new image. It's recommended to preload the new image in the `init` function.

**Comment by destata** [comment]
thanks williammalone.. let me try and learn about this..
